workflows:
  ios-release-workflow:
    name: iOS Release Workflow
    environment:
      groups:
        - app_store_credentials
    scripts:
      - name: Download and unpack Xcode ZIP
        script: |
          curl -L "https://www.dropbox.com/scl/fi/npbm1nteuf6apx0q25c2y/Little-Explorers-iOS.zip?rlkey=1w8lao27og2nyxaicxe4nk3s8&st=e6hft9s8&dl=1" -o project.zip
          unzip project.zip -d xcode_project
      - name: Build IPA
        script: |
          cd xcode_project
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build/Unity-iPhone.xcarchive \
            -allowProvisioningUpdates archive
          xcodebuild -exportArchive \
            -archivePath build/Unity-iPhone.xcarchive \
            -exportOptionsPlist <(echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><plist version=\"1.0\"><dict><key>method</key><string>app-store</string></dict></plist>") \
            -exportPath build
