workflows:
  ios-release-workflow:
    name: iOS Release Workflow
    environment:
      groups:
        - app_store_credentials
    scripts:
      - name: Download and unpack Xcode ZIP
        script: |
          curl -L "https://www.dropbox.com/scl/fi/xewf4bjrps2e2fzeeuzma/Little-Explorers-iOS.zip?rlkey=dfuo9jyhfmh7oxfszwy00ie1c&st=8x539tx5&dl=1" -o project.zip
          unzip project.zip -d xcode_project
      - name: Build IPA
        script: |
          cd xcode_project
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build/Unity-iPhone.xcarchive \
            -allowProvisioningUpdates archive
          xcodebuild -exportArchive \
            -archivePath build/Unity-iPhone.xcarchive \
            -exportOptionsPlist <(echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
            <plist version=\"1.0\">
              <dict>
                <key>method</key>
                <string>app-store</string>
                <key>provisioningProfiles</key>
                <dict>
                  <key>com.horizongames.littleexplorers</key>
                  <string>LittleExplorers_AppStore_Profile</string>
                </dict>
                <key>signingStyle</key>
                <string>manual</string>
                <key>teamID</key>
                <string>ZJUXC3QL59</string>
                <key>compileBitcode</key>
                <false/>
              </dict>
            </plist>") \
            -exportPath build
