workflows:
  ios-release-workflow:
    name: iOS Release Workflow
    environment:
      groups:
        - app_store_credentials
    scripts:
      - name: Download and unpack Xcode ZIP
        script: |
          curl -L "YOUR_NEW_DROPBOX_LINK?dl=1" -o project.zip
          unzip project.zip -d xcode_project
      - name: Build IPA
        script: |
          cd xcode_project
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build/Unity-iPhone.xcarchive archive
          xcodebuild -exportArchive \
            -archivePath build/Unity-iPhone.xcarchive \
            -exportOptionsPlist <(echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><plist version=\"1.0\"><dict><key>method</key><string>app-store</string></dict></plist>") \
            -exportPath build
