workflows:
  ios-release-workflow:
    name: iOS Release Workflow
    environment:
      ios_signing:
        provisioning_profiles:
          com.horizongames.littleexplorers: Profiles/LittleExplorers_AppStore_Profile.mobileprovision
      groups:
        - app_store_credentials
    scripts:
      - name: Download and unpack Xcode ZIP
        script: |
          curl -L "https://www.dropbox.com/scl/fi/gm9xi1adl3z6xghlucrm7/Little-Explorers.zip?rlkey=t4qcrpnyoqoc4vhfdnpkcz3rb&st=pg8jo5io&dl=1" -o project.zip
          unzip project.zip -d xcode_project
      - name: Build IPA
        script: |
          cd xcode_project
          xcodebuild -workspace LittleExplorers.xcworkspace \
            -scheme LittleExplorers \
            -configuration Release \
            -archivePath build/LittleExplorers.xcarchive archive
          xcodebuild -exportArchive \
            -archivePath build/LittleExplorers.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build
    publishing:
      app_store_connect: {}
